config/routes.rb
DeviseTest::Application.routes.draw do
  devise_for :users
  
  get "static/index"
  get "static/public"
  get "static/private"
  
  root "static#index"
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  attr_accessible :email, :password, :password_confirmation, :username, :first_name, :last_name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :update_sanitized_params, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
 
  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :username, :first_name, :last_name, :password, :password_confirmation)}
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
  
  def public
  end

  def private
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Default - <%= @page_title || "no title given" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <header>
      <div class="inner">      
        <h1 class="title"><%= @page_title %></h1>
        <nav>
          <li><%= link_to "private", static_private_path, class: "button" %></li>
          <li><%= link_to 'public', static_public_path, class: "button" %></li>
          <li><%= link_to 'home', root_path, class: "button" %></li>
        </nav>
      </div>
    </header>
  
  

    <%= yield %>

  </body>
</html>